services:
  - type: web
    name: bfblago
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm start
    nodeVersion: "20.18.0"
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://bfblago.onrender.com
    autoDeploy: true
